In [1]:
import numpy as np

In [2]:
# create an array
x = np.array([45,22,13,56,78,54,17])

In [3]:
print(x)

[45 22 13 56 78 54 17]


In [4]:
x

array([45, 22, 13, 56, 78, 54, 17])

In [5]:
type(x)

numpy.ndarray

In [6]:
x[3]

56

In [7]:
x[3] = 87
x

array([45, 22, 13, 87, 78, 54, 17])

In [8]:
x.dtype

dtype('int64')

In [12]:
y = np.array([45,22,13,56,78.67,54,17])

In [13]:
y

array([45.  , 22.  , 13.  , 56.  , 78.67, 54.  , 17.  ])

In [14]:
y[2]

13.0

In [15]:
y.dtype

dtype('float64')

In [16]:
x.size

7

In [18]:
x.min()

13

In [19]:
x.mean(), x.max(), x.sum(), 

(45.142857142857146, 87, 316)

In [20]:
x

array([45, 22, 13, 87, 78, 54, 17])

In [21]:
x + 10

array([55, 32, 23, 97, 88, 64, 27])

In [22]:
x * 2

array([ 90,  44,  26, 174, 156, 108,  34])

In [23]:
x / 3

array([15.        ,  7.33333333,  4.33333333, 29.        , 26.        ,
       18.        ,  5.66666667])

In [24]:
x > 40

array([ True, False, False,  True,  True,  True, False])

In [25]:
x[x > 40]

array([45, 87, 78, 54])

In [26]:
x[5]

54

In [27]:
x

array([45, 22, 13, 87, 78, 54, 17])

In [28]:
y = np.array([10,54,11,75,44,78,22])

In [29]:
x + y

array([ 55,  76,  24, 162, 122, 132,  39])

In [30]:
x - y

array([ 35, -32,   2,  12,  34, -24,  -5])

In [31]:
num = np.arange(10)
num

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
num = np.arange(3, 10)
num

array([3, 4, 5, 6, 7, 8, 9])

In [33]:
num = np.arange(1,10,2)
num

array([1, 3, 5, 7, 9])

In [34]:
z = np.zeros(10)

In [35]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
z = np.zeros(10, dtype = np.int16)

In [37]:
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [38]:
o = np.ones(10, dtype = np.int16)

In [39]:
o

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

##### Two dimensional array

In [41]:
num = np.array([[5,6,7],[2,1,3],[7,6,8],[9,0,2]])

In [42]:
num

array([[5, 6, 7],
       [2, 1, 3],
       [7, 6, 8],
       [9, 0, 2]])

In [43]:
num.shape

(4, 3)

In [44]:
type(num)

numpy.ndarray

In [45]:
num[2][1]

6

In [46]:
num[2][1] = 10

In [47]:
num

array([[ 5,  6,  7],
       [ 2,  1,  3],
       [ 7, 10,  8],
       [ 9,  0,  2]])

In [48]:
num.flatten()

array([ 5,  6,  7,  2,  1,  3,  7, 10,  8,  9,  0,  2])

In [49]:
num.T

array([[ 5,  2,  7,  9],
       [ 6,  1, 10,  0],
       [ 7,  3,  8,  2]])

In [ ]:
num.